AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-dynamo-db-test

  Sample SAM Template for api-dynamo-db-test
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  FetchAllUsersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: FetchAllUsers
      CodeUri: api-by-lambda-mongodb/
      Handler: app.fetchAllUsers
      Runtime: nodejs18.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
      Architectures:
        - x86_64
      Events:
        FetchAllUsersAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/fetchAllUsers
            Method: GET

  FetchAllUsersFunction2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: FetchAllUsers2
      CodeUri: api-by-lambda-mongodb/
      Handler: app.fetchAllUsers2
      Runtime: nodejs18.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      Architectures:
        - x86_64
      Events:
        FetchAllUsersAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/fetchAllUsers2
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FetchAllUsersAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  FetchAllUsersFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FetchAllUsersFunction.Arn
  FetchAllUsersFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FetchAllUsersFunctionRole.Arn
